### PR TITLE
Version 1.8

### PR DESCRIPTION
**Pull request by valk-ryx**
Redesigned plus and minus buttons
Redesigned set theme button
New design for the auto restart checkbox
Updated requirements.txt to include pywinstyles
Updated slider 1's name to "Opacity" to make it more obvious as to its function
Updated slider 2's name to "Intensity" to make it more obvious as to its function
Fixed capitilisation issues scattered around the app

### CODE REVIEW

**Comment by Andrew-J-Larson** [comment]
> pywinstyles

??? I assume typo?

**Comment by valk-ryx** [comment]
> > pywinstyles
> 
> ??? I assume typo?

No, it's not a typo, it's using pywinstyles to change the window border.

**Comment by Andrew-J-Larson** [comment]
> pywinstyles

It's missing from your file: https://github.com/neurokitti/Arc_Palette/blob/ca1bcc713ec666c5cbfd6796a5176309df4e7555/requirements.txt

**Comment by valk-ryx** [comment]
> > pywinstyles
> 
> It's missing from your file: https://github.com/neurokitti/Arc_Palette/blob/ca1bcc713ec666c5cbfd6796a5176309df4e7555/requirements.txt

Ah, tysm

**Pull request closed without merging**
